# This file defines the two services to be deployed on Render

services:
  # Flask API Service
  - type: web
    name: flask-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:10000 app:app"
    ports:
      - port: 10000

  # Streamlit Dashboard Service
  - type: web
    name: streamlit-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run dashboard.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - port: 8501
    envVars:
      - key: FLASK_API_URL
        # This uses Render's internal service discovery.
        # It's the URL of the other service we defined above.
        value: "http://flask-api.onrender.com"
